# Generated by Django 3.2.11 on 2022-04-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_figure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='caption',
        ),
    ]
